displayName=Map of Alacrity
author=Sacca
description=Displays Map of Alacrity shortcut locations on the world map and lets you teleport to them directly
tags=Alacrity,league,map,worldmap,teleport
plugins=com.mapofalacrity.MapOfAlacrityPlugin
